### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ohyeah521** [BenzoRom64/benzo_manifest#2]

**Comment by mydongistiny** [comment]
If you don't know how to build roms then go read some documentation first. QUIT POSTING HERE. You've been spamming all over Google+ XDA and here.

**Comment by ohyeah521** [comment]
I'm really sorry, I really was in these places are submitted bug, but did not discuss, I went to Google + speech, shielding you I speak, I have compiled official AOSP code, I don't know you this modified version of the Google of what are the similarities and differences. Is my own environmental problems, or your code problem. But your document is really too little, I Google for a long time simply can not find.
